create table credits
(
    CreditId     bigint generated by default as identity (start with 1 increment by 1),
    InterestRate double,
    CreditTerm   int,
    ClientId     bigint,
    primary key (CreditId),

    foreign key (ClientId) references clients (ClientId)
);