create table clients
(
    ClientId        bigint generated by default as identity (start with 1 increment by 1),
    Name            varchar(15),
    Surname         varchar(20),
    SecondName      varchar(25),
    TelephoneNumber varchar(15),
    Email           varchar(70),
    PassportNumber  varchar(12),
    primary key (clientId)
);
